### ISSUE TITLE
No module named 'diffusers'

### ISSUE THREAD

**Issue by dtch1997** [kxh001/ITdiffusion#1]
I followed the instructions in the docs to run `scripts/finetune.py`: 

```
python ./scripts/fine_tune.py --data_train_dir ~/Documents/data/cifar_train/ --data_test_dir ~/Documents/data/cifar_test/ --model_path models/cifar10_uncond_vlb_50M_500K.pt --image_size 32 --num_channels 128 --num_res_blocks 3 --learn_sigma True --dropout 0.3 --iddpm True --wrapped True --train_batch_size 32 --test_batch_size 256 --lr 2.5e-5 --epoch 10 --test True
```

I got the error: 
```
Traceback (most recent call last):
  File "./scripts/fine_tune.py", line 9, in <module>
    from utilsitd.script_util import (
  File "/home/daniel/Documents/github/ITdiffusion/utilsitd/script_util.py", line 6, in <module>
    from .unet import UNetModel, WrapUNetModel, WrapUNet2DModel
  File "/home/daniel/Documents/github/ITdiffusion/utilsitd/unet.py", line 21, in <module>
    from diffusers import UNet2DModel
ModuleNotFoundError: No module named 'diffusers'
```

**Comment by kxh001** [comment]
I've fixed the bug and cleaned up the repo. You could try it again. Thanks for your comments!
